### ISSUE TITLE
Once the animation is stopped, A spinner with full view is showing 

### ISSUE THREAD

**Issue by krishnakirana** [entotsu/TKSubmitTransition#42] opened 2018-01-07 12:40 UTC

**Comment by RishabhTayal** [comment] 2018-01-15 13:49
@krishnakirana Could you provide more detailed information? Screenshot? Video?

**Comment by RishabhTayal** [comment] 2018-02-06 18:49
This issue is open for long time. Need further clarification on what the issue is. Please open a new one with more info. Closing for now.

**Closed by RishabhTayal** 2018-02-06 18:49 UTC
